-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Master Outlet Table
CREATE TABLE IF NOT EXISTS outlets (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    branch_code VARCHAR(10) UNIQUE NOT NULL, 
    name TEXT NOT NULL,
    region TEXT CHECK (region IN ('Jabodetabek', 'Bandung')), 
    address TEXT,
    coordinates POINT, 
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Master Product Table
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    sku VARCHAR(50) UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    min_stock INTEGER DEFAULT 0, 
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Daily Ops Table (Z-STOP Engine)
CREATE TABLE IF NOT EXISTS daily_inventory_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id UUID REFERENCES outlets(id) ON DELETE CASCADE,
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    stock_qty INTEGER NOT NULL DEFAULT 0,
    sales_qty INTEGER NOT NULL DEFAULT 0,
    snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    -- Constraint to prevent duplicate snapshot entries
    UNIQUE(outlet_id, product_id, snapshot_date)
);

-- Performance Indexes for Daily Ops
CREATE INDEX IF NOT EXISTS idx_inventory_snapshot_date ON daily_inventory_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_inventory_outlet_id ON daily_inventory_snapshots(outlet_id);
-- Composite index for specific lookups
CREATE INDEX IF NOT EXISTS idx_inventory_lookup ON daily_inventory_snapshots(outlet_id, snapshot_date);

-- 4. Market Radar Table
CREATE TABLE IF NOT EXISTS market_trends (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_type VARCHAR(50), 
    title TEXT NOT NULL,
    summary TEXT, 
    sentiment_score NUMERIC(3,2), 
    is_viral BOOLEAN DEFAULT false,
    detected_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Sentiment Map Table
CREATE TABLE IF NOT EXISTS store_reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    outlet_id UUID REFERENCES outlets(id) ON DELETE CASCADE,
    reviewer_name TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    sentiment_label TEXT, 
    review_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Smart Alerts Table
CREATE TABLE IF NOT EXISTS system_alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    alert_type TEXT NOT NULL, 
    severity TEXT CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    message TEXT NOT NULL,
    is_resolved BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
